services:
  webhook-receiver:
    image: harishsivakumar/webhook-receiver:latest
    container_name: webhook-receiver
    ports:
      - "8080:8080"
    environment:
      - BATCH_SIZE=5
      - BATCH_INTERVAL=10s
      - POST_ENDPOINT=https://webhook.site/5ebbd1d7-9a83-4272-a5e6-8a2b3d085df1
    restart: unless-stopped